server:
  port: 9090

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings

logging:
  level:
    com:
      sm:
        noteApp: TRACE
    reactor:
      netty:
        http:
          client: TRACE
    org:
      springframework:
        web:
          reactive: TRACE
        cloud:
          gateway: TRACE

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:h2:file:./data/userdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
